name: phpstan
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          php-version: '8.0'

      - uses: "ramsey/composer-install@v1"
        with:
          composer-options: "--ignore-platform-reqs"

      - name: PHPStan
        uses: chindit/actions-phpstan@master
        with:
          # Arguments to add to PHPStan
          arguments: 'src/ --level=7'